/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    MazAvatar: typeof import('maz-ui/components/MazAvatar')['default']
    MazBtn: typeof import('maz-ui/components/MazBtn')['default']
    MazCard: typeof import('maz-ui/components/MazCard')['default']
    MazCardSpotlight: typeof import('maz-ui/components/MazCardSpotlight')['default']
    MazCheckbox: typeof import('maz-ui/components/MazCheckbox')['default']
    MazChip: typeof import('maz-ui/components/MazChip')['default']
    MazDialog: typeof import('maz-ui/components/MazDialog')['default']
    MazInput: typeof import('maz-ui/components/MazInput')['default']
    MazInputTags: typeof import('maz-ui/components/MazInputTags')['default']
    MazRadio: typeof import('maz-ui/components/MazRadio')['default']
    MazSelect: typeof import('maz-ui/components/MazSelect')['default']
    MazSlider: typeof import('maz-ui/components/MazSlider')['default']
    MazToaster: typeof import('maz-ui/components/MazToaster')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
