# Generated by Django 5.1.7 on 2025-03-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_alter_userprofile_meat_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fish_consumption',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vegetable_consumption',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
